server:
  port: 8082 # Puerto para este microservicio
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ # URL del Servidor de Descubrimiento

spring:
  cloud:

    compatibility-verifier:
      enabled: false # Deshabilita la verificaci√≥n que causa el fallo de arranque.
    # ---------------------------------------------------