server:
  port: 8081 # Puerto único para el servicio de tráfico
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ # URL del Servidor Eureka

spring:
  cloud:

    compatibility-verifier:
      enabled: false # Deshabilita la verificación que causa el fallo de arranque.
    # ---------------------------------------------------