server:
  port: 8761 # Puerto estándar para el servidor Eureka

eureka:
  client:
    # Indica que este servidor NO debe intentar registrarse a sí mismo como un servicio.
    register-with-eureka: false
    # Indica que este servidor NO necesita recuperar el registro de otros servicios.
    fetch-registry: false